# Build frontend assets
FROM docker.io/library/node:18-alpine AS build
WORKDIR /app
COPY frontend/package*.json ./
RUN npm ci
COPY frontend/ .
RUN npm run build

# Serve with Caddy
FROM docker.io/library/caddy:alpine
COPY containers/Caddyfile /etc/caddy/Caddyfile
COPY --from=build /app/dist /usr/share/caddy
EXPOSE 80 443
